spring.application.name=api
spring.datasource.url=jdbc:postgresql://ep-restless-frog-ats488d9-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_y3PaVNuUK8md

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect